django_example/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('admin/', admin.site.urls),
    path('todo/', include('todo.urls')),
    path('api/todo/', include('todo_apis.urls')),
    path('about/', views.about, name='about')
]

django_example/todo/urls.py
from django.urls import path
from todo import views
app_name = 'todo'

urlpatterns = [
    path('', views.list_view, name='index'),
    path('new', views.add, name='add'),
    path('<int:pk>', views.detail_view, name='detail'),
    path('<int:pk>/edit', views.edit, name='edit'),
    path('<int:pk>/delete', views.delete, name='delete')
]

# /todo/34

django_example/todo_apis/urls.py
from django.urls import path
from rest_framework.urlpatterns import format_suffix_patterns

from todo_apis import views

app_name = 'todo_apis'

urlpatterns = [
    path('', views.tasks_apiview),
    path('<int:pk>', views.task_apiview)
]

urlpatterns = format_suffix_patterns(urlpatterns)

django_example/todo/models.py
from django.db import models

ASSIGNED_TO = (
    ('1', 'user1'),
    ('2', 'user2'),
    ('3', 'user3'),
)


# Create your models here.
class Task(models.Model):
    name = models.CharField(max_length=100)
    assigned_to = models.CharField(max_length=1, choices=ASSIGNED_TO, default='1')
    finished = models.BooleanField(default=False)
    description = models.TextField(blank=True, default='')

    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.name} -- {self.get_assigned_to_display()}"

django_example/todo_apis/models.py
from django.db import models

# Create your models here.

django_example/mysite/forms.py
from django import forms


class AboutForm(forms.Form):
    email = forms.EmailField()
    contact = forms.CharField(max_length=10)

django_example/todo/forms.py
from django import forms

from todo.models import Task


class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = '__all__'

django_example/mysite/views.py
from django.shortcuts import render

from .forms import AboutForm


def index(reqeust):
    return render(reqeust, 'index.html', {})


def about(request):
    form = AboutForm(request.POST or None)

    final_message = ""
    if request.method == 'POST':
        if form.is_valid():
            email = form.cleaned_data.get('email')
            contact = form.cleaned_data.get('contact')
            final_message = f'Thanks for subscribing. you will get weekly update on {email}/{contact}'
            # form = AboutForm()

    return render(request, 'about.html', {'form': form, 'final_message': final_message})

django_example/todo/views.py
from django.shortcuts import render, get_object_or_404, reverse, redirect

from todo.forms import TaskForm
# Create your views here.
from todo.models import Task


def list_view(request):
    task_list = Task.objects.all()

    return render(request, 'todo/index.html', {'task_list': task_list})


def detail_view(request, pk):
    task_obj = get_object_or_404(Task, pk=pk)
    return render(request, 'todo/detail.html', {'task_obj': task_obj})


def add(request):
    form = TaskForm(request.POST or None)

    if request.method == 'POST':
        if form.is_valid():
            obj = form.save()
            return redirect(reverse('todo:detail', kwargs={'pk': obj.pk}))
        else:
            return render(request, 'todo/task_form.html', {'form': form, 'type': 'add'})

    return render(request, 'todo/task_form.html', {'form': form, 'type': 'ADD'})


def edit(request, pk):
    obj = get_object_or_404(Task, pk=pk)
    form = TaskForm(request.POST or None, instance=obj)
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            return redirect(reverse('todo:detail', kwargs={'pk': pk}))
    return render(request, 'todo/task_form.html', {'form': form, 'type': 'UPDATE'})


def delete(request, pk):
    obj = get_object_or_404(Task, pk=pk)
    obj.delete()
    return redirect(reverse('todo:index'))

django_example/todo_apis/views.py
from rest_framework import status
from rest_framework.decorators import api_view
from rest_framework.response import Response

# Create your views here.
from todo.models import Task
from todo_apis.serializers import TaskSerializer


@api_view(['GET', 'POST'])
def tasks_apiview(request, format=None):
    if request.method == 'GET':
        tasks = Task.objects.all()
        serializer = TaskSerializer(tasks, many=True)
        return Response(serializer.data, status=status.HTTP_200_OK)
    if request.method == 'POST':
        serializer = TaskSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(
                serializer.data,
                status=status.HTTP_201_CREATED
            )
        return Response(
            serializer.errors,
            status=status.HTTP_400_BAD_REQUEST
        )


@api_view(['GET', 'PUT', 'PATCH', 'DELETE'])
def task_apiview(request, pk, format=None):
    try:
        task = Task.objects.get(pk=pk)
    except Task.DoesNotExist:
        return Response({'status': 'notfound'}, status=status.HTTP_404_NOT_FOUND)

    if request.method == 'GET':
        sr = TaskSerializer(task)
        return Response(sr.data, status.HTTP_200_OK)

    elif request.method == 'PUT':
        sr = TaskSerializer(task, data=request.data)
        if sr.is_valid():
            sr.save()
            return Response(sr.data, status.HTTP_200_OK)
        else:
            return Response(sr.errors, status.HTTP_400_BAD_REQUEST)

    elif request.method == 'PATCH':
        sr = TaskSerializer(task, data=request.data, partial=True)
        if sr.is_valid():
            sr.save()
            return Response(sr.data, status.HTTP_200_OK)
        else:
            return Response(sr.errors, status.HTTP_400_BAD_REQUEST)

    elif request.method == 'DELETE':
        task.delete()
        resp = {
            'deleted': 'ok'
        }
        return Response(resp, status.HTTP_204_NO_CONTENT)

django_example/templates/about.html
{% extends 'base.html' %}

{% block content %}
    <h2>About us </h2>
    <p>Lorrem ipsum Lorrem ipsum Lorrem ipsum Lorrem ipsum Lorrem ipsum Lorrem ipsum </p>

    <h3>Subscribe to newsletter</h3>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Subscribe</button>
    </form>

    {% if final_message %}
        <p>{{ final_message }}</p>
    {% endif %}

{% endblock %}

django_example/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <style>
        nav ul li {
            list-style: none;
            display: inline-block;
        }

        .button {
            border-radius: 40px;
            padding: 5px 10px;
            margin: 5px;
        {#border: 1px solid black;#} text-decoration: none;
        }

        .green {
            background: forestgreen;
            color: white;
        }

        .blue {
            background: dodgerblue;
            color: white;
        }

        .orange {
            background: darkorange;
            color: black;
        }

        .red {
            background: red;
            color: white;
        }

    </style>
</head>
<body>
<div>
    <nav>
        <ul>
            <li><a class="button blue" href="{% url 'index' %}">Home</a></li>
            <li><a class="button blue" href="{% url 'todo:index' %}">Tasks</a></li>
            <li><a class="button blue" href="{% url 'about' %}">About</a></li>
        </ul>
    </nav>

    {% block content %}
    {% endblock %}
</div>

</body>
</html>

django_example/templates/index.html
{% extends 'base.html' %}

{% block content %}
    <h2>Welcome to main page</h2>
    <img src="https://static.djangoproject.com/img/logos/django-logo-negative.png" alt="django">

{% endblock %}

django_example/todo/templates/todo/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <style>
        nav ul li {
            list-style: none;
            display: inline-block;
        }

        .button {
            border-radius: 40px;
            padding: 5px 10px;
            margin: 5px;
        {#border: 1px solid black;#} text-decoration: none;
        }

        .green {
            background: forestgreen;
            color: white;
        }

        .blue {
            background: dodgerblue;
            color: white;
        }

        .orange {
            background: darkorange;
            color: black;
        }

        .red {
            background: red;
            color: white;
        }

    </style>
</head>
<body>
<div>
    <nav>
        <ul>
            <li><a class="button blue" href="{% url 'index' %}">Home</a></li>
            <li><a class="button blue" href="{% url 'todo:index' %}">Tasks</a></li>
            <li><a class="button green" href="{% url 'todo:add' %}">Add new</a></li>
        </ul>
    </nav>
    {% block content %}
    {% endblock %}
</div>

</body>
</html>

django_example/todo/templates/todo/confirm_delete.html
{% extends 'todo/base.html' %}

{% block content %}
    <h2>Delete Confirm</h2>
    <a href="">yes</a>
    <h3>{{ task_obj.name }}</h3>
    <p>id: {{ task_obj.pk }}</p>
    <p>is_finished: {{ task_obj.finished }}</p>
    <p>
        <a href="{% url 'todo:edit' task_obj.pk %}">edit</a>
        <a href="#">Delete</a>
    </p>

{% endblock %}

django_example/todo/templates/todo/detail.html
{% extends 'todo/base.html' %}

{% block content %}
    <h2>Task Detail</h2>
    <h3>{{ task_obj.name }}
        <span style="font-size: .8em; color: rgba(0, 0, 0, 0.5)">
            Assigned to: {{ task_obj.get_assigned_to_display }}
        </span>
    </h3>
    <p>id: {{ task_obj.pk }}</p>
    <p>is_finished: {{ task_obj.finished }}</p>
        <p>description: {{ task_obj.description }}</p>
    <p>
        <a class='button orange' href="{% url 'todo:edit' task_obj.pk %}">edit</a>
        <a class='button red' href="{% url 'todo:delete' task_obj.pk %}">Delete</a>
    </p>

{% endblock %}

django_example/todo/templates/todo/index.html
{% extends 'todo/base.html' %}

{% block content %}
    <h2>Task list</h2>
    <ol>

        {% for task in task_list %}
            <li>
                <a href="{% url 'todo:detail' task.id %}">{{ task }}</a>

            </li>

        {% endfor %}
    </ol>

{% endblock %}

django_example/todo/templates/todo/task_form.html
{% extends 'todo/base.html' %}

{% block content %}
    <h1>Add task</h1>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="button blue" type="submit">{{ type }}</button>
    </form>
{% endblock %}